import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import { Card } from '../components/cards/cards'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet"></link>
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <img src='pizzalogo.png'></img>
          <nav className={styles.navheader}>
            <ul>
              <li className={styles.select}>
                <p>Home</p>
              </li>
              <li>
                <p>Menu</p>
              </li>
              <li>
                <p>Promo</p>
              </li>
              <li><img src='lupa.png'></img></li>
              <li><img src='loja.png'></img></li>
              <li><button>SIGN IN</button></li>
            </ul>
          </nav>
          <nav className={styles.mobile}>
            <img src='menu.png'></img>
          </nav>
        </header>
        <section className={styles.fridaypizza}>
          <div className={styles.first}>
            <h2>Friday pizza!</h2>
            <h3>Time to enjoy our delicious pizza.</h3>
            <button>ORDER NOW</button>
          </div>
          <div className={styles.gradient}>

          </div>
          <div className={styles.second}>
            
          </div>
        </section>
        <section className={styles.recommended}>
          <h2>Recommended menu</h2>
          <div className={styles.cards}>
            <Card 
            image='cheeselovers.png'
            name='Cheese Lovers'
            description='Combination of Alfredo sauce and two cheeses – Romano, and Parmesan.'
            price='$20.00'
            />
            <Card 
            image='pepperonipizza.png'
            name='Pepperoni Pizza'
            description='Pizza with homemade spicy beef sausage'
            price='$25.00'
            />
            <Card 
            image='margheritapizza.png'
            name='margheritapizza'
            description='Made with San Marzano tomatoes, mozzarella cheese, and fresh basil.'
            price='$35.00'
            />
          </div>
        </section>
      </main>

    </div>
  )
}
